steps:
- script: |
   wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
   tar -xzvf ScaResolver-linux64.tar.gz
   rm -rf ScaResolver-linux64.tar.gz
  displayName: 'Sca Resolver'


-script
  sudo apt install mavem npm
  displayName:'Sca Resolver package manager step'


- task: CmdLine@2
  env:
   SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: Sca Resolver package resolution
  inputs:
    script: "./ScaResolver offline -s . -r .cxsca-results.json -n project-name --log-level Debug --maven-parameters='-s $(System.DefaultWorkingDirectory)/devops/ci/settings.xml' "
  
- task: Checkmarx AST@2
  displayName: Checkmarx AST
  inputs:
    CheckmarxService: 7fb34e3e-07bd-418f-af9b-a9d80a49e637
    tenantName: beta_nova8

