version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    security_opt: # IAC
      - no-new-privileges:true
    deploy: # IAC
      resources:
        limits:
          cpus: "4.0"
          memory: 200M
    networks: # IAC
      - mynetwork
#    security_opt:    - no-new-privileges:true
  web:
    build: .
    image: pygoat/pygoat
    command: gunicorn --bind 0.0.0.0:8000 --workers 6 pygoat.wsgi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - migration
      - db
    networks:
      - frontend
      - backend
  migration:
    image: pygoat/pygoat
    command: python pygoat/manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db
